//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2501_Kon_Vol.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ID_content { get; set; }
        public Nullable<int> Tarif { get; set; }
        public string Operator { get; set; }
        public string Cena { get; set; }
    
        public virtual Tarif Tarif1 { get; set; }
    }
}
